In [4]:
import pandas as pd
import numpy as mp

In [5]:
df = pd.read_sas('../raw_datasets/p5191.sas7bdat')
df.head()

sex  rcmv  graftype   age  intxsurv  dead  kps  anc  intxanc  dwoanc  ...  \
0  2.0   1.0       2.0  15.0      6.68   1.0  1.0  1.0     0.39     0.0  ...   
1  2.0   0.0       1.0   1.0     96.71   0.0  1.0  1.0     0.53     0.0  ...   
2  1.0   1.0       1.0   3.0    120.89   0.0  1.0  1.0     0.99     0.0  ...   
3  1.0   0.0       1.0  12.0     82.96   0.0  1.0  1.0     0.39     0.0  ...   
4  1.0   0.0       3.0  13.0     95.72   0.0  2.0  1.0     0.86     0.0  ...   

   agvhd24  intxagvhd24  dwoagvhd24  intxefs  secondary_malig  intx2malig  \
0      1.0         0.59         0.0     0.69              0.0         NaN   
1      0.0        96.71         0.0    96.71              0.0         NaN   
2      0.0       120.89         0.0   120.89              0.0         NaN   
3      0.0        82.96         0.0    82.96              0.0         NaN   
4      1.0         1.32         0.0    95.72              0.0         NaN   

   stroke  acs    dummyid   dummyccn  
0     1.0  0.0  1746133.0  4028482.0  
1     0.0  0.0  1405938.0  4028570.0  
2     0.0  0.0  1400962.0  4028574.0  
3     0.0  0.0  1542462.0  4027460.0  
4     0.0  0.0  1549746.0  4028456.0  

[5 rows x 40 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 847 entries, 0 to 846
Data columns (total 40 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   sex              847 non-null    float64
 1   rcmv             847 non-null    float64
 2   graftype         847 non-null    float64
 3   age              847 non-null    float64
 4   intxsurv         847 non-null    float64
 5   dead             847 non-null    float64
 6   kps              847 non-null    float64
 7   anc              847 non-null    float64
 8   intxanc          847 non-null    float64
 9   dwoanc           847 non-null    float64
 10  platelet         847 non-null    float64
 11  intxplatelet     847 non-null    float64
 12  dwoplatelet      847 non-null    float64
 13  cgvhd            847 non-null    float64
 14  intxcgvhd        847 non-null    float64
 15  dwocgvhd         847 non-null    float64
 16  gf               847 non-null    float64
 17  intxgf          

In [18]:
df['donorgp'].unique()

array([4., 1., 2., 3.])

In [7]:
df['genotype'].unique()

array([1., 2.])

In [8]:
df['sex'].unique()

array([2., 1.])

In [9]:
df['graftype'].unique()

array([2., 1., 3.])

In [10]:
df['hla_match'].unique()

array([3., 1., 2.])

In [11]:
df['condint'].unique()

array([1., 3., 2.])

In [12]:
df['gvhdgp'].unique()

array([6., 7., 5., 2., 4., 1., 3., 8., 9.])

In [13]:
df['dead'].unique()

array([1., 0.])

In [14]:
df['gf'].unique()

array([1., 0.])

In [15]:
df['agvhd24'].unique()

array([ 1.,  0., 99.])

In [16]:
df['cgvhd'].unique()

array([0., 1.])

In [17]:
df['anc'].unique()

array([1., 0.])