In [38]:
import pandas as pd
import numpy as np

In [39]:
df = pd.read_sas('../raw_datasets/p5303.sas7bdat')
df.head()

yeartx  sex  disease        age  graftype  ragecat  gvhdgp  ethgp   kps  \
0  2005.0  2.0     10.0   2.061602       1.0      0.0     9.0    1.0   1.0   
1  2005.0  2.0     10.0  11.353867      22.0      1.0     5.0    1.0   0.0   
2  2005.0  1.0     10.0  17.245722      22.0      1.0     5.0    6.0   1.0   
3  2006.0  1.0     20.0   1.089665       1.0      0.0     9.0    1.0  99.0   
4  2006.0  2.0     20.0   1.713895       1.0      0.0     5.0   99.0   1.0   

   invivo_tcd  ...  d_cen_regions_num  d_tel_regions_num  d_B_Content_alt  \
0         1.0  ...                2.0                2.0              2.0   
1         1.0  ...                1.0                1.0              1.0   
2         0.0  ...                2.0                2.0              2.0   
3         0.0  ...                2.0                1.0              1.0   
4         1.0  ...                1.0                1.0              1.0   

   d_score_B_Content_ranking_num  kir_composite_score  disgrade  d_2DS1_NEW  \
0                            2.0                  3.0       2.0         1.0   
1                            1.0                  3.0       2.0         0.0   
2                            2.0                  3.0       2.0         1.0   
3                            1.0                  2.0       2.0         0.0   
4                            1.0                  3.0       2.0         0.0   

   d_b_content   pseudoccn    pseudoid  
0          2.0  20192516.0  20388748.0  
1          0.0  20192520.0  20198125.0  
2          2.0  20192569.0  20207878.0  
3          1.0  20189583.0  20234291.0  
4          0.0  20192661.0  20386517.0  

[5 rows x 40 columns]

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 713 entries, 0 to 712
Data columns (total 40 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   yeartx                         713 non-null    float64
 1   sex                            713 non-null    float64
 2   disease                        713 non-null    float64
 3   age                            713 non-null    float64
 4   graftype                       713 non-null    float64
 5   ragecat                        713 non-null    float64
 6   gvhdgp                         713 non-null    float64
 7   ethgp                          713 non-null    float64
 8   kps                            713 non-null    float64
 9   invivo_tcd                     713 non-null    float64
 10  indxtx2                        710 non-null    float64
 11  dead                           713 non-null    float64
 12  intxsurv                       710 non-null    flo

In [41]:
df.columns.to_list()

['yeartx',
 'sex',
 'disease',
 'age',
 'graftype',
 'ragecat',
 'gvhdgp',
 'ethgp',
 'kps',
 'invivo_tcd',
 'indxtx2',
 'dead',
 'intxsurv',
 'anc',
 'intxanc',
 'platelet',
 'intxplatelet',
 'agvhd24',
 'intxagvhd24',
 'agvhd34',
 'intxagvhd34',
 'cgvhd',
 'intxcgvhd',
 'rel',
 'trm',
 'dfs',
 'intxrel',
 'condint',
 'yrgrp',
 'd_haplotypes_num',
 'd_cen_regions_num',
 'd_tel_regions_num',
 'd_B_Content_alt',
 'd_score_B_Content_ranking_num',
 'kir_composite_score',
 'disgrade',
 'd_2DS1_NEW',
 'd_b_content',
 'pseudoccn',
 'pseudoid']

In [42]:
to_nan = [99.]
df.replace(to_replace=to_nan, value=np.nan, inplace=True)

In [43]:
df['agvhd24'].unique()

array([ 0.,  1., nan])

In [44]:
df['anc'].unique()

array([1., 0.])

In [45]:
df['cgvhd'].unique()

array([ 0.,  1., nan])

In [46]:
df['condint'].unique()

array([1., 3., 2.])

In [47]:
df['dead'].unique()

array([0., 1.])

In [48]:
df['disease'].unique()

array([10., 20.])

In [49]:
df['disgrade'].unique()

array([ 2.,  1.,  3.,  4., nan])

In [50]:
df['ethgp'].unique()

array([ 1.,  6., nan,  3.,  2.,  5.,  4.])

In [51]:
df['graftype'].unique()

array([ 1., 22.])

In [52]:
df['gvhdgp'].unique()

array([ 9.,  5.,  4.,  6., 11., 10.,  8.,  7.])

In [53]:
df['rel'].unique()

array([ 0.,  1., nan])

In [54]:
df['sex'].unique()

array([2., 1.])

In [55]:
df['trm'].unique()

array([ 0.,  1., nan])