In [68]:
import pandas as pd
import numpy as np

In [69]:
uae_df = pd.read_excel('../raw_datasets/uae.xlsx')
uae_df.head()

R_Sex        Age Adult Categorey  Nationality  Hemaological Diagnosis  \
0    MALE  38.356164             NaN  BANGLADESHI  Acute myeloid leukemia   
1  FEMALE  28.657534           Adult      EMIRATI  Acute myeloid leukemia   
2  FEMALE  37.249315           Adult       INDIAN  Acute myeloid leukemia   
3    MALE  51.619178           Adult     EGYPTIAN  Acute myeloid leukemia   
4    MALE  52.117808           Adult       SYRIAN  Acute myeloid leukemia   

  PreBMT Treatment Regimen 1 PreBMT Treatment Regimen 2  \
0                        7+3                      HIDAC   
1                        7+3                   FLAG/IDA   
2                        7+3                      HIDAC   
3                        7+3                      HIDAC   
4                        7+3                      HIDAC   

  PreBMT Treatment Regimen 3  Number of lines of Rx before BMT  \
0                        NaN                                 2   
1                Azacytidine                                 4   
2                        NaN                                 2   
3                   FLAG/IDA                                 3   
4                   FLAG/IDA                                 3   

      Indication for  BMT  ...            GVHD Prophylaxis  GVHD   \
0  Acute myeloid leukemia  ...             Cyclosporin+MTX     NO   
1  Acute myeloid leukemia  ...  MMF+Tacrolimus+Ruxolitinib    YES   
2  Acute myeloid leukemia  ...             Cyclosporin+MTX    YES   
3  Acute myeloid leukemia  ...             Cyclosporin+MTX    YES   
4  Acute myeloid leukemia  ...             Cyclosporin+MTX    YES   

  GVHD Acute/Chronic  GVHD severity  SKIN CGVHD LIVER CGVHD GI CGVHD  \
0                 NaN            NaN         NO          NO       NO   
1               Acute       MODERATE         NO         YES       NO   
2             Chronic         SEVERE         NO          NO       NO   
3             Chronic           MILD         NO         YES       NO   
4               Acute         SEVERE        YES          NO      YES   

  EYE CGVHD LUNG CGVHD DEAD/Y/N  
0        NO         NO       NO  
1        NO         NO      YES  
2       YES         NO       NO  
3        NO         NO       NO  
4        NO         NO      YES  

[5 rows x 27 columns]

In [70]:
uae_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91 entries, 0 to 90
Data columns (total 27 columns):
 #   Column                            Non-Null Count  Dtype  
---  ------                            --------------  -----  
 0   R_Sex                             91 non-null     object 
 1   Age                               91 non-null     float64
 2   Adult Categorey                   40 non-null     object 
 3   Nationality                       91 non-null     object 
 4   Hemaological Diagnosis            91 non-null     object 
 5   PreBMT Treatment Regimen 1        40 non-null     object 
 6   PreBMT Treatment Regimen 2        31 non-null     object 
 7   PreBMT Treatment Regimen 3        14 non-null     object 
 8   Number of lines of Rx before BMT  91 non-null     int64  
 9   Indication for  BMT               91 non-null     object 
 10  Diagnosis to BMT time months      91 non-null     int64  
 11  R_Age at BMT                      91 non-null     int64  
 12  R_Blood gr

In [71]:
uae_df.columns.to_list()

['R_Sex',
 'Age',
 'Adult Categorey',
 'Nationality',
 'Hemaological Diagnosis',
 'PreBMT Treatment Regimen 1',
 'PreBMT Treatment Regimen 2',
 'PreBMT Treatment Regimen 3',
 'Number of lines of Rx before BMT',
 'Indication for  BMT',
 'Diagnosis to BMT time months',
 'R_Age at BMT',
 'R_Blood group',
 'HLA match',
 'NEW HLA',
 'D_relation',
 'D_sex',
 'GVHD Prophylaxis',
 'GVHD ',
 'GVHD Acute/Chronic ',
 'GVHD severity ',
 'SKIN CGVHD',
 'LIVER CGVHD',
 'GI CGVHD',
 'EYE CGVHD',
 'LUNG CGVHD',
 'DEAD/Y/N']

In [72]:
to_nan = ['UNKNOWN', 'Unknown', 'U']
uae_df.replace(to_replace=to_nan, value=np.nan, inplace=True)

/var/folders/03/xqwlspkx04x3bk4y2js4ql0r0000gn/T/ipykernel_92133/1656636187.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  uae_df.replace(to_replace=to_nan, value=np.nan, inplace=True)


In [73]:
uae_df['R_Sex'].unique()

array(['MALE', 'FEMALE'], dtype=object)

In [74]:
uae_df['Nationality'].unique()

array(['BANGLADESHI', 'EMIRATI', 'INDIAN', 'EGYPTIAN', 'SYRIAN',
       'PAKISTANI', 'AFGHANISTAN', 'YEMENI', 'SUDANESE', 'ETHIOPIAN'],
      dtype=object)

In [75]:
uae_df['Hemaological Diagnosis'].unique()

array(['Acute myeloid leukemia', 'Aplastic anemia', 'B-ALL',
       'Beta thalassemia intermedia', 'Beta thalassemia major',
       'Chronic Granulomatous Disease',
       'Combined Variable Immunodeficiency', 'Dyskeratosis congentia',
       'Fanconi anemia', 'Hemophagocytic lymphohistiocytosis (HLH)',
       'Hodgkin lymphoma ', 'Multiple myeloma', 'Multiple Myeloma',
       'Myelodysplastic Syndrome', 'Myelofibrosis',
       'Myeloproliferative disorder ', 'Neuroblastoma',
       'Non Hodgkin Lymphoma', 'SCID', 'Sickle Cell Disease', 'T-ALL'],
      dtype=object)

In [76]:
uae_df['HLA match'].unique()

array(['10 OF 10', '10 of 10', '5 of 10', '6 of 10', '9 of 10', nan,
       '12 of 12'], dtype=object)

In [77]:
uae_df['NEW HLA'].unique()

array([1. , 0.5, 0.6, 0.9, nan])

In [78]:
uae_df['D_relation'].unique()

array(['BROTHER', 'UNRELATED', 'SON', 'SISTER', 'FATHER', 'MOTHER',
       'DAUGHTER', 'UNCLE', 'SELF', 'COUSIN'], dtype=object)

In [79]:
uae_df['D_sex'].unique()

array(['Male', nan, 'Female', 'MALE'], dtype=object)

In [80]:
uae_df['GVHD Prophylaxis'].unique()

array(['Cyclosporin+MTX', 'MMF+Tacrolimus+Ruxolitinib',
       'Cyclophosphamide+MMF+Tacrolimus', nan, 'Tacrolimus',
       'Cyclosporin', 'Cyclosporin+MTX+Tacrolimus', 'Cyclosporin+MMF',
       'Tacrolimus+MMF', 'Tacrolimus+MTX', 'MMF+Tacrolimus+MTX',
       'Cyclophosphamide+MMF', 'Sirolimus',
       'Cyclophosphamide+MMF+Sirolimus', 'MMF', 'Cyclosporin+Abatacept',
       'Cyclophosphamide+MMF+Tacrolimus+Ruxolitinib',
       'Cyclosporin+MTX+MMF+Leflunomide+Sirolimus',
       'Cyclophosphamide+MMF+Tacrolimus+Cyclosporin',
       'Cyclosporin+MTX+ Abatacept'], dtype=object)

In [81]:
uae_df['GVHD '].unique()

array(['NO', 'YES'], dtype=object)

In [82]:
uae_df['GVHD Acute/Chronic '].unique()

array([nan, 'Acute', 'Chronic'], dtype=object)

In [83]:
uae_df['GVHD severity '].unique()

array([nan, 'MODERATE', 'SEVERE', 'MILD'], dtype=object)

In [84]:
uae_df['DEAD/Y/N'].unique()

array(['NO', 'YES', nan], dtype=object)